# Generated by Django 4.2.4 on 2023-09-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.CharField(max_length=50),
        ),
    ]
